#ddev-generated
services:
  s3-http-proxy:
    container_name: ddev-${DDEV_SITENAME}-s3-http-proxy
    image: codemonauts/s3-http-proxy
    networks: [default, ddev_default]
    restart: "always"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      # See https://github.com/codemonauts/s3-http-proxy/blob/main/README.md
      S3PROXY_BUCKET: ""
      S3PROXY_REGION: "eu-central-1"
      S3PROXY_PORT: 3000
      S3PROXY_CACHING: ""
      S3PROXY_SIZELIMIT: 104857600
      S3PROXY_LOGGING: "WARN"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
